export const spanishBeauty = [
  'Cepillo de pelo',
  'Peine',
  'Secador de pelo',
  'Plancha de pelo',
  'Rizador',
  'Maquillaje',
  'Base',
  'Corrector',
  'Rubor',
  'Sombra de ojos',
  'Delineador',
  'Máscara de pestañas',
  'Pintalabios',
  'Esmalte de uñas',
  'Quitaesmalte',
  'Lima de uñas',
  'Cortaúñas',
  'Crema hidratante',
  'Protector solar',
  'Perfume',
  'Desodorante',
  'Jabón',
  'Champú',
  'Acondicionador',
  'Gel de ducha',
  'Exfoliante',
  'Cremas faciales',
  'Cremas corporales',
  'Aceite de coco',
  'Bálsamo labial',
  'Cepillo de dientes',
  'Hilo dental',
  'Enjuague bucal',
  'Maquinilla de afeitar',
  'Crema de afeitar',
  'Afeitadora eléctrica',
  'Espejo',
  'Toalla',
  'Algodón',
  'Papel higiénico',
  'Cesto de basura',
  'Esponja',
  'Bañera',
  'Báscula',
  'Espejo de aumento',
  'Vaporizador facial',
  'Sauna',
  'Jacuzzi',
  'Velas aromáticas',
  'Sales de baño',
  'Toallitas desmaquillantes',
];
