export const spanishPublicPlaces = [
  'Restaurante',
  'Cine',
  'Biblioteca',
  'Museo',
  'Parque',
  'Estación de tren',
  'Aeropuerto',
  'Centro comercial',
  'Playa',
  'Iglesia',
  'Hospital',
  'Escuela',
  'Estadio',
  'Cafetería',
  'Bar',
  'Teatro',
  'Piscina',
  'Gimnasio',
  'Zoológico',
  'Supermercado',
  'Iglesia',
  'Plaza',
  'Estación de autobuses',
  'Hotel',
  'Ayuntamiento',
  'Banco',
  'Oficina de correos',
  'Gasolinera',
  'Puerto',
  'Cementerio',
  'Acuario',
  'Feria',
  'Estación de policía',
  'Estación de bomberos',
  'Biblioteca',
  'Casa de la cultura',
  'Centro de convenciones',
  'Cancha deportiva',
  'Parque de diversiones',
  'Salón de belleza',
  'Spa',
  'Club nocturno',
  'Sala de conciertos',
  'Palacio de justicia',
  'Embajada',
  'Sinagoga',
];
