export const spanishTransportation = [
  'Coche',
  'Avión',
  'Barco',
  'Tren',
  'Bicicleta',
  'Autobús',
  'Tranvía',
  'Metro',
  'Camión',
  'Motocicleta',
  'Helicóptero',
  'Submarino',
  'Patines',
  'Patineta',
  'Carroza',
  'Triciclo',
  'Jet privado',
  'Dirigible',
  'Monopatín',
  'Lancha',
  'Furgoneta',
  'Buggy',
  'Camioneta',
  'Velero',
  'Yate',
  'Segway',
  'Carretilla',
  'Carro de golf',
  'Camión de bomberos',
  'Ambulancia',
  'Taxi',
  'Funicular',
  'Barcaza',
  'Góndola',
  'Balsa',
  'Tobogán acuático',
  'Bote de remos',
  'Quad',
  'Parapente',
  'Moto de nieve',
  'Riksja',
  'Tobogán de hielo',
  'Tren de montaña',
  'Barco de vela',
  'Carro de mano',
  'Triciclo de carga',
  'Scooter',
];
