import { ManifestOptions } from 'vite-plugin-pwa';

export const manifestOptions: Partial<ManifestOptions> = {
  name: 'Nofun Games',
  short_name: 'Nofun',
  description: 'On the go games to play with friends',
  lang: 'en',
  categories: ['games', 'entertainment'],
  dir: 'ltr',
  icons: [
    { src: '/favicon.ico', type: 'image/x-icon', sizes: '16x16 32x32' },
    { src: '/icon-192.png', type: 'image/png', sizes: '192x192' },
    { src: '/icon-512.png', type: 'image/png', sizes: '512x512' },
    {
      src: '/icon-192-maskable.png',
      type: 'image/png',
      sizes: '192x192',
      purpose: 'maskable',
    },
    {
      src: '/icon-512-maskable.png',
      type: 'image/png',
      sizes: '512x512',
      purpose: 'maskable',
    },
  ],
  file_handlers: [],
  start_url: '/?source=pwa',
  id: '/?source=pwa',
  scope: '/',
  // scope_extensions: [],
  display: 'standalone',
  // display_override: [],
  orientation: 'portrait',
  theme_color: '#0F172A',
  background_color: '#FDFDFD',
  // related_applications: [],
  prefer_related_applications: false,
  // protocol_handlers: [],
  shortcuts: [
    {
      name: 'Spy Game',
      short_name: 'Spy',
      description: "Discover the impostor before it's too late.",
      url: '/spy?source=pwa',
      icons: [{ src: '/images/spy-icon.png', sizes: '192x192' }],
    },
    {
      name: 'Papelito Game',
      short_name: 'Papelito',
      description: 'Make your team guess as many words as possible.',
      url: '/papelito?source=pwa',
      icons: [{ src: '/images/spy-icon.png', sizes: '192x192' }],
    },
    {
      name: 'Dice Game',
      short_name: 'Dice',
      description: 'Roll the dice and take your chances.',
      url: '/dice?source=pwa',
      icons: [{ src: '/images/spy-icon.png', sizes: '192x192' }],
    },
  ],
  screenshots: [],
  // iarc_rating_id: '',
  share_target: {
    action: '/shared-content-receiver/',
    method: 'GET',
    params: {
      title: 'Nofun',
      text: 'Read Papelito QR Code',
      url: 'link',
    },
  },
  handle_links: 'auto',
};
