export const englishBeauty = [
  'Hairbrush',
  'Comb',
  'Hair dryer',
  'Hair straightener',
  'Curling iron',
  'Makeup',
  'Foundation',
  'Concealer',
  'Blush',
  'Eyeshadow',
  'Eyeliner',
  'Mascara',
  'Lipstick',
  'Nail polish',
  'Nail polish remover',
  'Nail file',
  'Nail clipper',
  'Moisturizer',
  'Sunscreen',
  'Perfume',
  'Deodorant',
  'Soap',
  'Shampoo',
  'Conditioner',
  'Shower gel',
  'Exfoliant',
  'Facial creams',
  'Body lotions',
  'Coconut oil',
  'Lip balm',
  'Toothbrush',
  'Dental floss',
  'Mouthwash',
  'Razor',
  'Shaving cream',
  'Electric shaver',
  'Mirror',
  'Towel',
  'Cotton',
  'Toilet paper',
  'Trash can',
  'Sponge',
  'Bathtub',
  'Scale',
  'Magnifying mirror',
  'Facial steamer',
  'Sauna',
  'Jacuzzi',
  'Aromatherapy candles',
  'Bath salts',
  'Makeup remover wipes',
];
