export const englishMoviesAndSeries = [
  'Titanic',
  'Harry Potter',
  'Star Wars',
  'Avengers',
  'Jurassic Park',
  'The Godfather',
  'Forrest Gump',
  'The Shawshank Redemption',
  'The Matrix',
  'The Lord of the Rings',
  'The Dark Knight',
  'Spider-Man',
  'Toy Story',
  'Frozen',
  'The Lion King',
  'The Little Mermaid',
  'Cinderella',
  'Aladdin',
  'Beauty and the Beast',
  'Finding Nemo',
  'The Incredibles',
  'Shrek',
  'Madagascar',
  'Despicable Me',
  'The Simpsons',
  'Friends',
  'Game of Thrones',
  'Breaking Bad',
  'Stranger Things',
  'The Witcher',
  'The Mandalorian',
  'The Crown',
  'La Casa de Papel',
  'Money Heist',
  'Black Mirror',
  'The Office',
  'FRIENDS',
  'How I Met Your Mother',
  'The Big Bang Theory',
  "Grey's Anatomy",
  'The Simpsons',
  'Family Guy',
  'South Park',
  'Rick and Morty',
  'Westworld',
  'The Walking Dead',
  'Black Panther',
  'Wonder Woman',
  'The Joker',
  'Iron Man',
  'Captain America',
  'Spider-Man',
  'Batman',
  'Superman',
  'Wonder Woman',
  'Thor',
];
