export const englishPublicPlaces = [
  'Restaurant',
  'Cinema',
  'Library',
  'Museum',
  'Park',
  'Train station',
  'Airport',
  'Shopping mall',
  'Beach',
  'Church',
  'Hospital',
  'School',
  'Stadium',
  'Cafeteria',
  'Bar',
  'Theater',
  'Swimming pool',
  'Gym',
  'Zoo',
  'Supermarket',
  'Square',
  'Bus station',
  'Hotel',
  'City hall',
  'Bank',
  'Post office',
  'Gas station',
  'Harbor',
  'Cemetery',
  'Aquarium',
  'Fair',
  'Police station',
  'Fire station',
  'Library',
  'Cultural center',
  'Convention center',
  'Sports field',
  'Amusement park',
  'Beauty salon',
  'Spa',
  'Nightclub',
  'Concert hall',
  'Courthouse',
  'Embassy',
  'Synagogue',
];
